#!/bin/sh

cd demo

python3 genBBOXData.py \
    --config-file ../configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml \
    --input  ../../learnable-triangulation-pytorch/data/cmupanoptic \
    --output ../../learnable-triangulation-pytorch/data/pretrained/cmu/mrcnn-detections \
    --opts MODEL.WEIGHTS ../model_final_280758.pkl

cd -